"""Create Chat Use Case

Simplified use case that directly creates chat via Prisma
"""

from typing import Any

from infrastructure.prisma_client import PrismaClient
from models.domain_errors import DomainErrors
from models.user import UserId
from repositories.user_repository import IUserRepository


class CreateChatUseCase:
    """Use case for creating a new chat"""

    def __init__(self, prisma_client: PrismaClient, user_repository: IUserRepository):
        self.prisma = prisma_client
        self.user_repository = user_repository

    async def execute(
        self, user_id: str, title: str | None = None
    ) -> Any:
        """Execute create chat use case

        Args:
            user_id: User ID who creates the chat
            title: Optional chat title (defaults to "新しいチャット")

        Returns:
            Prisma chat data (with UUID v7 generated by DB)

        Raises:
            DomainError: If user does not exist or other domain error occurs
        """
        user_id_obj = UserId(user_id)

        # Validate user exists
        user = await self.user_repository.find_by_id(user_id_obj)
        if not user:
            raise DomainErrors.user_not_found(user_id)

        # Set default title if needed
        if title is None or title.strip() == "":
            title = "新しいチャット"

        # Create chat directly in database (UUID v7 auto-generated)
        chat_data = await self.prisma.client.chat.create(
            data={
                "userId": user_id,  # Use string directly
                "title": title.strip(),
            }
        )

        return chat_data
